### ISSUE TITLE
目录索引需求

### ISSUE THREAD

**Issue by J-Z-Z** [Dragonrster/The-Powder-Toy-V96#1]
hi  [Dragonrster](https://github.com/Dragonrster)， 你的TPT中文文档非常棒， 

pdf文档是否可以有一个目录视图， 这样可以方便在看文档的时候通过侧边栏进行查找和索引。

**Comment by Dragonrster** [comment]
> [你好 Dragonrster](https://github.com/Dragonrster)， 你的TPT中文文档非常棒，
> 
> pdf文档是否可以有一个目录视图，这样可以方便在看文档的时候通过侧边栏进行查找和索引。

OK,我已经完成了目录视图,并针对Kindle等低ppi电子书设备的图片优化

**Comment by J-Z-Z** [comment]
速度超快

**Comment by J-Z-Z** [comment]
well done.
